In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn.linear_model
from program_synthesis.synthesizer import Synthesizer
from program_synthesis.utils import calcF1

In [2]:
from data.loader import DataLoader
loader = DataLoader()
train_primitive_matrix, val_primitive_matrix, test_primitive_matrix, \
            train_ground, val_ground, test_ground, \
            train_plots, val_plots, test_plots = loader.load_data(None, "./data/imdb/")



/Users/yeechoongchan/miniconda3/envs/NST/lib/python3.8/site-packages/sklearn/feature_extraction/text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Mapping, defaultdict


In [3]:
print(train_primitive_matrix[:,:4])
np.array_equal(train_primitive_matrix[:,1], train_primitive_matrix[:,3])

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


False

In [4]:
# Step 1. synthesizer
model = sklearn.linear_model.LogisticRegression
synthesizer = Synthesizer(model, train_primitive_matrix, train_ground, 1)
H, X_comb = synthesizer.solve()

64it [00:00, 638.09it/s]

322 choose 2


322it [00:00, 697.69it/s]


In [5]:
print(np.sum(X_comb[0]))
print()
print(np.sum(X_comb[1]))
np.array_equal(X_comb[3], X_comb[1])

print(len(X_comb))
print(len(H))

0

1
322
322


In [6]:
X_comb[:10]

[(0,), (1,), (2,), (3,), (4,), (5,), (6,), (7,), (8,), (9,)]

In [7]:
# verify training accuracy
F1s = []
i= 0
for h_comb, x_comb in zip(H, X_comb):
    i += 1
    h, beta = h_comb
    try:
        y_L = h.predict(train_primitive_matrix[:, np.array(x_comb)])
    except ValueError as e:
        print(i)
        print(h.coef_)
        print(x_comb.shape)
        print(h)
        print(e)
        break
        
    f_score = calcF1(train_ground, y_L, beta)
    F1s.append(f_score)
print(F1s)
print('max', max(F1s))

[0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5484154929577465, 0.5448943661971831, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5545774647887324, 0.5448943661971831, 0.5431338028169014, 0.5431338028169014, 0.5748239436619719, 0.5545774647887324, 0.5730633802816901, 0.5448943661971831, 0.5484154929577465, 0.5431338028169014, 0.5475352112676056, 0.5431338028169014, 0.5492957746478874, 0.5440140845070423, 0.5440140845070423, 0.5431338028169014, 0.5448943661971831, 0.5466549295774648, 0.5589788732394366, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5440140845070423, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014,

In [8]:
## Pruning

In [9]:
from program_synthesis.pruner import Pruner

In [10]:
H_C = []
n = np.zeros(len(val_primitive_matrix))
w = 0.5

In [11]:
train_primitive_matrix.shape

(1136, 322)

In [12]:
val_primitive_matrix.shape

(284, 322)

In [13]:
pruner = Pruner(H, H_C, train_ground, train_primitive_matrix, val_primitive_matrix, n, w, X_comb)

In [14]:
h_best = pruner.prune()

[[0.54035956 0.45964044]
 [0.54035956 0.45964044]
 [0.54035956 0.45964044]
 ...
 [0.54035956 0.45964044]
 [0.54035956 0.45964044]
 [0.54035956 0.45964044]]


NameError: name 'a' is not defined

In [ ]:
h_best

In [ ]:

calcJaccard()