In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn.linear_model
from program_synthesis.synthesizer import Synthesizer
from program_synthesis.utils import calcF1

In [2]:
from data.loader import DataLoader
loader = DataLoader()
train_primitive_matrix, val_primitive_matrix, test_primitive_matrix, \
            train_ground, val_ground, test_ground, \
            train_plots, val_plots, test_plots = loader.load_data(None, "./data/imdb/")



In [3]:
print(train_primitive_matrix[:,:4])
np.array_equal(train_primitive_matrix[:,1], train_primitive_matrix[:,3])

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


False

In [4]:
# Step 1. synthesizer
model = sklearn.linear_model.LogisticRegression
synthesizer = Synthesizer(model, train_primitive_matrix, train_ground)
H, X_comb = synthesizer.solve()

14it [00:00, 133.10it/s]

322 choose 3


322it [00:01, 206.70it/s]
51681it [04:29, 191.53it/s]


In [5]:
print(len(X_comb))
print(X_comb[0].shape, X_comb[1].shape, X_comb[2].shape)
print(train_primitive_matrix.shape)

52003
(1136, 1) (1136, 1) (1136, 1)
(1136, 322)


In [6]:
print(np.sum(X_comb[0]))
print()
print(np.sum(X_comb[1]))
np.array_equal(X_comb[3], X_comb[1])

print(len(X_comb))
print(len(H))

25

25
52003
52003


In [7]:
# verify training accuracy
F1s = []
i= 0
for h_comb, x_comb in zip(H, X_comb):
    i += 1
    h, beta = h_comb
    try:
        y_L = h.predict(x_comb)
    except ValueError as e:
        print(i)
        print(h.coef_)
        print(x_comb.shape)
        print(h)
        print(e)
        break
        
    f_score = calcF1(train_ground, y_L, beta)
    F1s.append(f_score)
print(F1s)
print('max', max(F1s))

[0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5484154929577465, 0.5448943661971831, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5545774647887324, 0.5448943661971831, 0.5431338028169014, 0.5431338028169014, 0.5748239436619719, 0.5545774647887324, 0.5730633802816901, 0.5448943661971831, 0.5484154929577465, 0.5431338028169014, 0.5475352112676056, 0.5431338028169014, 0.5492957746478874, 0.5440140845070423, 0.5440140845070423, 0.5431338028169014, 0.5448943661971831, 0.5466549295774648, 0.5589788732394366, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5440140845070423, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014, 0.5431338028169014,